### ISSUE TITLE
No need for tf.tidy() around model.predict() ?

### ISSUE THREAD

**Issue by hideya** [yukagil/tfjs-mnist-cnn-demo#1]
Thanks for the nice example, which helped me a lot!
I'm a beginner of tfjs, and got a question about the following line:

https://github.com/yukagil/tfjs-mnist-cnn-demo/blob/b778715e92250d4642b8c18a37d8d1fbdf662640/index.html#L133

Checking google's example like the following, `tf.tidy()` is used around `model.predict()` to fee up GPU memory automatically:

https://github.com/tensorflow/tfjs-examples/blob/bf51024bd04fa6197b410db10e5210d4604aef43/mnist/index.js#L115

I'm wondering whether it is needed for the case of this example.
Could you share any thoughts on this?

**Comment by yukagil** [comment]
It's exactly as you said.
Fixed this issue in #2 
Thanks for the feedback!!

**Comment by hideya** [comment]
Looks great!
It was great to see that you actually checked the memory usage and made sure it is really doing the job!
I'm closing this as fixed.
